FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Entrena y genera el modelo
RUN python train.py

EXPOSE 8000

CMD ["sh", "-c", "cd Modelos_ml/RegresionLineal/back && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]